name: Terraform Pipeline

env: &aws_cred
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  pull_request:
    branches:
      - develop
      - main
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4
      
      - name: Confirma instalação do Terraform
        run: terraform version

      - name: Inicializar backend do Terraform
        run: terraform init
      
      - name: Terraform Plan
        run: terraform plan
        env:
          <<: *aws_cred
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          <<: *aws_cred